ARG HTTP1_PORT
ARG HTTP2_PORT

FROM connect_crosstest_base as builder

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 \
    go build -ldflags "-s -w" -trimpath -o /go/bin/serverconnect ./cmd/server/serverconnect

FROM alpine:3.15.3

ARG H1_PORT
ARG H2_PORT
ENV H1_PORT=$H1_PORT
ENV H2_PORT=$H2_PORT

COPY --from=builder /go/bin/serverconnect /usr/local/bin/serverconnect

ENTRYPOINT /usr/local/bin/serverconnect --h1port $H1_PORT --h2port $H2_PORT
