FROM connect_crosstest_base as builder

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 \
    go build -ldflags "-s -w" -trimpath -o /go/bin/client ./cmd/client

FROM alpine:3.15.3

ARG HOST
ARG PORT
ARG IMPLEMENTATION
ENV HOST=$HOST
ENV PORT=$PORT
ENV IMPLEMENTATION=$IMPLEMENTATION

COPY --from=builder /go/bin/client /usr/local/bin/client

ENTRYPOINT /usr/local/bin/client --host="$HOST" --port="$PORT" --implementation="$IMPLEMENTATION"
