FROM connect_crosstest_base as builder

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 \
    go build -ldflags "-s -w" -trimpath -o /go/bin/servergrpc ./cmd/server/servergrpc

FROM alpine:3.15.3

ARG PORT
ENV PORT=$PORT

COPY --from=builder /go/bin/servergrpc /usr/local/bin/servergrpc

ENTRYPOINT /usr/local/bin/servergrpc --port $PORT
