name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: head
      - uses: actions/checkout@v4
        with:
          path: base
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: bufbuild/buf-action@v1
        with:
          input: head/proto
          breaking_against: base/proto
          token: ${{ secrets.BUF_TOKEN }}
