name: conformance-web
on:
  schedule:
    - cron: '14 10 * * *' # Runs 14:10 UTC, 10:10 Eastern
  workflow_dispatch: # support manual runs
    inputs:
      test_protobuf_es_branch:
        description: 'Target protobuf-es branch to test'
        required: false
        default: 'main'
      test_connect_web_branch:
        description: 'Target connect-web branch to test'
        required: false
        default: 'main'
      disable_open_issue:
        description: 'Disable open issue on fail'
        type: boolean
        required: false
        default: false
permissions:
  contents: read
  issues: write
jobs:
  conformance-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx # Docker Buildkit required for docker-compose
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true
      - name: Setup environment variables for test
        run: |
          echo "TEST_PROTOBUF_ES_BRANCH=${{ github.event.inputs.test_protobuf_es_branch || 'main' }}" >> $GITHUB_ENV
          echo "TEST_CONNECT_WEB_BRANCH=${{ github.event.inputs.test_connect_web_branch || 'main' }}" >> $GITHUB_ENV
          echo "DISABLE_OPEN_ISSUE=${{ github.event.inputs.disable_open_issue || false }}" >> $GITHUB_ENV
      - name: Test Web Clients With Latest Commit
        run: make dockercomposetestweb # Make target includes clean-up
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
      - name: Open Issue on Fail
        uses: dblock/create-a-github-issue@v3
        if: ${{ failure() && env.DISABLE_OPEN_ISSUE != 'true' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          filename: .github/conformance-issue-template.md
          update_existing: true
          search_existing: open
